server:
  port: 9002

spring:
  application:
    name: dym_file
  servlet:
    #文件上传大小限制
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

      #max-file-size: -1  #取消大小限制

#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  #注册到 eureka 上面供其他实例访问的地址使用 ip 进行注册，其他实例会通过 ip 进行访问
  instance:
    prefer-ip-address: true

#fastDFS文件系统的tracker地址
FILE_SERVER_URL: http://192.168.128.128:8080
